name: build
on: [pull_request, push]

jobs:
  versions:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: list supported versions
        id: list
        run: |
          list=$(ls gradle | grep -E '^[0-9]+(_[0-9]+)+\.versions\.toml$' | sed 's/\.versions\.toml$//; s/_/./g' | jq -R . | jq -sc .)
          echo "matrix=$list" >> "$GITHUB_OUTPUT"

  build-matrix:
    needs: versions
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.versions.outputs.matrix) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew :${{ matrix.version }}:build
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.version }}
          path: build/libs/*-${{ matrix.version }}.jar

  build:
    runs-on: ubuntu-24.04
    needs: build-matrix
    if: always()
    steps:
      - name: check matrix result
        if: ${{ needs.build-matrix.result != 'success' }}
        run: exit 1
